import { TemplateEngine } from "../../scaffold/template-engine.js";
import {
  buildGeneratedFile,
  type DimensionResolver,
  type ResolveContext,
  type ResolveResult,
  type GeneratedFile,
} from "../dimension-resolver.js";

export class CoverageResolver implements DimensionResolver {
  readonly dimension = "coverage";

  canResolve(ctx: ResolveContext): boolean {
    return ctx.currentScore < 5;
  }

  async resolve(ctx: ResolveContext): Promise<ResolveResult> {
    const generatedFiles: GeneratedFile[] = [];
    const warnings: string[] = [];

    switch (ctx.techStack) {
      case "dotnet": {
        try {
          const engine = new TemplateEngine();
          const content = engine.render("resolve/coverage/coverlet.runsettings", {
            version: "resolve",
          });
          generatedFiles.push(buildGeneratedFile(ctx, "coverlet.runsettings", content));
        } catch (error) {
          warnings.push(`Failed to render coverlet template: ${error instanceof Error ? error.message : String(error)}`);
        }
        break;
      }

      case "typescript": {
        // Generate a .nycrc.json for c8/istanbul coverage if no config exists
        const nycConfig = JSON.stringify({
          "all": true,
          "reporter": ["text", "lcov", "cobertura"],
          "exclude": ["node_modules", "dist", "coverage", "**/*.test.*", "**/*.spec.*"],
          "branches": 80,
          "lines": 80,
          "functions": 80,
          "statements": 80,
        }, null, 2) + "\n";
        generatedFiles.push(buildGeneratedFile(ctx, ".nycrc.json", nycConfig));
        break;
      }

      case "python": {
        // Generate a .coveragerc for coverage.py
        const coveragerc = [
          "[run]",
          "branch = True",
          "source = .",
          "omit =",
          "    */tests/*",
          "    */test_*.py",
          "    */__pycache__/*",
          "    */.venv/*",
          "",
          "[report]",
          "fail_under = 80",
          "show_missing = True",
          "",
          "[xml]",
          "output = coverage.xml",
          "",
        ].join("\n");
        generatedFiles.push(buildGeneratedFile(ctx, ".coveragerc", coveragerc));
        break;
      }

      case "java": {
        // JaCoCo requires pom.xml modification — generate a snippet file
        const snippet = [
          "<!-- JaCoCo plugin — add to your pom.xml <build><plugins> section -->",
          "<!-- Generated by dafke resolve -->",
          "<plugin>",
          "  <groupId>org.jacoco</groupId>",
          "  <artifactId>jacoco-maven-plugin</artifactId>",
          "  <version>0.8.12</version>",
          "  <executions>",
          "    <execution>",
          "      <goals><goal>prepare-agent</goal></goals>",
          "    </execution>",
          "    <execution>",
          "      <id>report</id>",
          "      <phase>test</phase>",
          "      <goals><goal>report</goal></goals>",
          "    </execution>",
          "  </executions>",
          "</plugin>",
          "",
        ].join("\n");
        generatedFiles.push(buildGeneratedFile(ctx, ".dafke/jacoco-snippet.xml", snippet));
        warnings.push("JaCoCo snippet generated — manually add it to your pom.xml <build><plugins> section.");
        break;
      }

      default: {
        // Generic coverage guidance file
        const content = [
          "# Coverage Setup Guide",
          "",
          `Your tech stack (${ctx.techStack}) was detected.`,
          "Please configure code coverage measurement for your test framework.",
          "",
          "Common tools by ecosystem:",
          "- JavaScript/TypeScript: c8, istanbul, vitest --coverage",
          "- Java: JaCoCo, Cobertura",
          "- .NET: Coverlet, dotCover",
          "- Python: coverage.py, pytest-cov",
          "",
          "Generated by dafke resolve.",
          "",
        ].join("\n");
        generatedFiles.push(buildGeneratedFile(ctx, ".dafke/coverage-guide.md", content));
        warnings.push("Could not generate specific coverage config for this tech stack. See .dafke/coverage-guide.md.");
        break;
      }
    }

    // Mutation testing for score 3+ (tech-stack-aware)
    if (ctx.currentScore >= 3) {
      switch (ctx.techStack) {
        case "typescript": {
          const strykerConfig = JSON.stringify({
            testRunner: "vitest",
            packageManager: "npm",
            mutate: ["src/**/*.ts", "!src/**/*.test.ts", "!src/**/*.d.ts"],
            reporters: ["html", "clear-text", "progress"],
            coverageAnalysis: "perTest",
          }, null, 2) + "\n";
          generatedFiles.push(buildGeneratedFile(ctx, "stryker.config.json", strykerConfig));
          break;
        }
        case "java": {
          const pitSnippet = [
            "<!-- PIT mutation testing — add to pom.xml <build><plugins> -->",
            "<!-- Generated by dafke resolve -->",
            "<plugin>",
            "  <groupId>org.pitest</groupId>",
            "  <artifactId>pitest-maven</artifactId>",
            "  <version>1.15.3</version>",
            "  <configuration>",
            "    <targetClasses><param>com.dafke.*</param></targetClasses>",
            "    <outputFormats><param>HTML</param></outputFormats>",
            "  </configuration>",
            "</plugin>",
            "",
          ].join("\n");
          generatedFiles.push(buildGeneratedFile(ctx, ".dafke/pitest-snippet.xml", pitSnippet));
          warnings.push("PIT mutation testing snippet generated — add to your pom.xml.");
          break;
        }
        case "python": {
          const mutmutConfig = [
            "# mutmut configuration — append to pyproject.toml or place as setup.cfg",
            "# Generated by dafke resolve",
            "[tool.mutmut]",
            'paths_to_mutate = "src/"',
            'runner = "pytest -x -q"',
            'tests_dir = "tests/"',
            "",
          ].join("\n");
          generatedFiles.push(buildGeneratedFile(ctx, ".dafke/mutmut-snippet.toml", mutmutConfig));
          warnings.push("mutmut config snippet generated — merge it into your pyproject.toml.");
          break;
        }
        case "dotnet": {
          const strykerDotnet = JSON.stringify({
            "stryker-config": {
              "project-info": { name: "dafke-project" },
              "mutation-level": "Standard",
              "reporters": ["html", "progress"],
            },
          }, null, 2) + "\n";
          generatedFiles.push(buildGeneratedFile(ctx, "stryker-config.json", strykerDotnet));
          break;
        }
        default:
          warnings.push(`No mutation testing tool available for ${ctx.techStack}. Consider Stryker (JS/TS/.NET) or PIT (Java).`);
          break;
      }
    }

    const hasMutation = generatedFiles.some((f) =>
      (f.relativePath.includes("stryker") || f.relativePath.includes("pitest") || f.relativePath.includes("mutmut")) && (f.written || ctx.dryRun),
    );

    return {
      dimension: this.dimension,
      generatedFiles,
      previousScore: ctx.currentScore,
      expectedScore: hasMutation ? Math.min(5, ctx.currentScore + 2) : Math.min(5, Math.max(1, ctx.currentScore + 1)),
      summary: hasMutation
        ? `Generated coverage + mutation testing config for ${ctx.techStack}.`
        : `Generated coverage configuration for ${ctx.techStack}.`,
      warnings,
    };
  }
}
