import { TemplateEngine } from "../../scaffold/template-engine.js";
import {
  buildGeneratedFile,
  type DimensionResolver,
  type ResolveContext,
  type ResolveResult,
  type GeneratedFile,
} from "../dimension-resolver.js";

export class ReviewResolver implements DimensionResolver {
  readonly dimension = "review";

  canResolve(ctx: ResolveContext): boolean {
    return ctx.currentScore < 5;
  }

  async resolve(ctx: ResolveContext): Promise<ResolveResult> {
    const generatedFiles: GeneratedFile[] = [];
    const warnings: string[] = [];

    const isGitHub = ctx.ciPlatform !== "azure-devops";

    // 1. CODEOWNERS
    const codeownersPath = isGitHub ? ".github/CODEOWNERS" : "CODEOWNERS";
    const codeownersContent = [
      "# CODEOWNERS — generated by dafke resolve",
      "# Replace @FIXME-add-team with your actual team handles.",
      "",
      "# Default reviewers for all files",
      "* @FIXME-add-team",
      "",
      "# Security-sensitive paths require security team review",
      "# src/auth/       @FIXME-add-team @FIXME-security-team",
      "# src/data/       @FIXME-add-team @FIXME-security-team",
      "",
    ].join("\n");
    generatedFiles.push(buildGeneratedFile(ctx, codeownersPath, codeownersContent));
    warnings.push("CODEOWNERS generated with placeholder teams — update @FIXME-add-team with real team handles.");

    // 2. PR template (GitHub-style)
    if (isGitHub) {
      try {
        const engine = new TemplateEngine();
        const content = engine.render("resolve/review/pull-request-template.md", {
          version: "resolve",
          prSizeLimit: String(ctx.rules.governance.prSizeLimit),
        });
        generatedFiles.push(buildGeneratedFile(ctx, ".github/PULL_REQUEST_TEMPLATE.md", content));
      } catch (error) {
        warnings.push(`Failed to render PR template: ${error instanceof Error ? error.message : String(error)}`);
      }
    } else {
      // Azure DevOps — generate a simpler PR template
      const content = [
        "## Description",
        "<!-- Brief description of what this PR changes and why. -->",
        "",
        "## AI Code Review Checklist",
        "- [ ] No hardcoded secrets or credentials",
        "- [ ] Error handling is comprehensive",
        `- [ ] PR is under ${ctx.rules.governance.prSizeLimit} lines changed`,
        "- [ ] Co-Authored-By header present for AI-assisted code",
        "- [ ] All tests pass",
        "",
      ].join("\n");
      generatedFiles.push(buildGeneratedFile(ctx, ".azuredevops/pull_request_template.md", content));
    }

    // 3. Branch protection config (GitHub only, probot/settings)
    if (isGitHub) {
      try {
        const engine = new TemplateEngine();
        const content = engine.render("resolve/review/branch-protection.yml", {
          version: "resolve",
        });
        generatedFiles.push(buildGeneratedFile(ctx, ".github/settings.yml", content));
        warnings.push("Branch protection via settings.yml requires the Probot Settings GitHub App to be installed.");
      } catch (error) {
        warnings.push(`Failed to render branch protection template: ${error instanceof Error ? error.message : String(error)}`);
      }
    }

    // 4. CodeRabbit AI review bot (for score 3→5)
    if (ctx.currentScore >= 3) {
      const coderabbitContent = [
        "# CodeRabbit AI code review — generated by dafke resolve",
        "language: en",
        "reviews:",
        "  profile: assertive",
        "  request_changes_workflow: true",
        "  high_level_summary: true",
        "  auto_review:",
        "    enabled: true",
        "    drafts: false",
        "chat:",
        "  auto_reply: true",
        "",
      ].join("\n");
      generatedFiles.push(buildGeneratedFile(ctx, ".coderabbit.yaml", coderabbitContent));
      warnings.push("CodeRabbit requires the CodeRabbit App to be installed on your repo.");
    }

    // Expected score
    const hasBot = generatedFiles.some((f) => f.relativePath === ".coderabbit.yaml" && (f.written || ctx.dryRun));
    const expectedScore = hasBot ? Math.min(5, ctx.currentScore + 3) : Math.min(5, Math.max(3, ctx.currentScore + 2));
    return {
      dimension: this.dimension,
      generatedFiles,
      previousScore: ctx.currentScore,
      expectedScore,
      summary: hasBot
        ? "Generated review config with AI review bot (CodeRabbit)."
        : "Generated CODEOWNERS, PR template with review checklist, and branch protection config.",
      warnings,
    };
  }
}
