/**
 * Step: Claude Code Hooks & Settings
 *
 * Generates .claude/settings.json (hooks), .claude/mcp.json (Playwright MCP),
 * and lefthook.yml for git hooks. GitHub-only — no Azure DevOps / GitNexus /
 * Context7, and no automatic update-check.
 */

import * as p from "@clack/prompts";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { execa } from "execa";
import { TemplateEngine } from "../../scaffold/template-engine.js";
import { VERSION } from "../../../version.js";
import type { WizardStepContext, WizardStepResult } from "../wizard-steps.js";

async function installLefthook(repoRoot: string): Promise<void> {
  try {
    await execa("npx", ["-y", "@evilmartians/lefthook", "install"], { cwd: repoRoot, timeout: 30_000 });
  } catch {
    try {
      await execa("lefthook", ["install"], { cwd: repoRoot, timeout: 10_000 });
    } catch {
      // lefthook not available — hooks won't be active but files are written
    }
  }
}

// AI-code-responsibility disclaimer shown once per session via a SessionStart hook.
const DISCLAIMER_TEXT = "⚠️  DISCLAIMER: Put it all together, and you, the human submitter, bear full responsibility and accountability for reviewing the AI-generated code, ensuring license compliance, and for any bugs or security flaws that arise.";

function buildDisclaimerHookCommand(): string {
  return `echo '${JSON.stringify({ systemMessage: DISCLAIMER_TEXT })}'`;
}

function buildSettings(): Record<string, unknown> {
  const check = "command -v dafke >/dev/null 2>&1";
  const warn = "echo 'dafke not found in PATH — install with: npm i -g dafke'";
  return {
    $schema: "https://json.schemastore.org/claude-code-settings.json",
    _comment: `Generated by dafke v${VERSION}. DO NOT EDIT MANUALLY — run 'dafke update' to refresh.`,
    hooks: {
      SessionStart: [
        {
          hooks: [
            { type: "command", command: buildDisclaimerHookCommand() },
            { type: "command", command: `${check} && dafke hook skills-check || true`, timeout: 10 },
            { type: "command", command: `${check} && dafke hook doc-check || true`, timeout: 5 },
          ],
        },
      ],
      PreToolUse: [
        {
          matcher: "Write|Edit|MultiEdit",
          hooks: [{ type: "command", command: `${check} && dafke hook pre-edit || ${warn}`, timeout: 5 }],
        },
        {
          matcher: "Bash",
          hooks: [{ type: "command", command: `${check} && dafke hook pre-bash || ${warn}`, timeout: 5 }],
        },
        {
          matcher: "Bash(git commit)",
          hooks: [{ type: "command", command: "npx tsc --noEmit 2>/dev/null && npm run lint 2>/dev/null || echo 'Pre-commit checks: typecheck or lint failed — review before committing'", timeout: 30 }],
        },
      ],
      PostToolUse: [
        {
          matcher: "Write|Edit",
          hooks: [{ type: "command", command: `${check} && dafke hook post-edit || ${warn}` }],
        },
        {
          matcher: "Bash",
          hooks: [{ type: "command", command: `${check} && dafke hook post-bash || ${warn}` }],
        },
      ],
      Stop: [
        {
          hooks: [{ type: "command", command: `${check} && dafke hook stop || ${warn}` }],
        },
      ],
    },
    permissions: {
      defaultMode: "auto",
      allow: ["Read", "Glob", "Grep", "Write", "Edit", "Bash"],
      deny: [],
    },
    model: "claude-opus-4-20250514",
    effortLevel: "high",
  };
}

function buildLefthook(): string {
  const engine = new TemplateEngine();
  return engine.getTemplate("hooks/lefthook.yml");
}

function buildMcpConfig(): Record<string, unknown> {
  return {
    mcpServers: {
      playwright: {
        command: "npx",
        args: ["-y", "@playwright/mcp@latest"],
        env: {},
        description: "Playwright — browser automation for testing and debugging web UIs",
      },
    },
  };
}

export async function execute(ctx: WizardStepContext): Promise<WizardStepResult> {
  const claudeDir = join(ctx.repoRoot, ".claude");
  const settingsPath = join(claudeDir, "settings.json");
  const mcpPath = join(claudeDir, "mcp.json");
  const lefthookPath = join(ctx.repoRoot, "lefthook.yml");

  const settings = buildSettings();
  const mcpConfig = buildMcpConfig();
  const lefthook = buildLefthook();

  p.log.message("Hooks to install:");
  p.log.message("  PreToolUse  - validates writes and bash commands");
  p.log.message("  PostToolUse - post-write validation");
  p.log.message("  Stop        - session cleanup");
  p.log.message("");
  p.log.message("Git hooks (via lefthook):");
  p.log.message("  pre-commit  - gitleaks + lint + typecheck");
  p.log.message("  pre-push    - test + security audit");
  p.log.message("  commit-msg  - conventional commits");

  const writeAll = async (): Promise<void> => {
    await mkdir(claudeDir, { recursive: true });
    await writeFile(settingsPath, JSON.stringify(settings, null, 2), "utf-8");
    await writeFile(mcpPath, JSON.stringify(mcpConfig, null, 2), "utf-8");
    await writeFile(lefthookPath, lefthook, "utf-8");
    await installLefthook(ctx.repoRoot);
  };

  if (ctx.nonInteractive) {
    await writeAll();
    p.log.success("Hooks, settings, and MCP config written");
    return { success: true, data: { hooksInstalled: true } };
  }

  const approve = await p.confirm({ message: "Install hooks and settings?" });
  if (p.isCancel(approve) || !approve) {
    p.log.info("Skipped hooks installation");
    return { success: true, data: { hooksInstalled: false } };
  }

  await writeAll();
  p.log.success("Written .claude/settings.json, .claude/mcp.json, and lefthook.yml (hooks activated)");
  return { success: true, data: { hooksInstalled: true } };
}
