/**
 * Rules generator — creates .claude/rules/ instruction files from templates.
 *
 * Global rules (always loaded) have no YAML frontmatter.
 * Tech-specific rules have `globs:` frontmatter for on-demand loading.
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { TemplateEngine } from "./template-engine.js";
import { atomicWrite } from "../../utils/fs.js";
import { VERSION } from "../../version.js";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Global rule templates — generated for every project, no frontmatter. */
const GLOBAL_RULES = ["architecture", "git-conventions", "mcp-tools"];

/** Version header pattern for detecting unmodified files. */
const VERSION_HEADER_PATTERN = /^# Generated by dafke v[\w.-]+ — do not edit manually$/m;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RuleGenerationResult {
  created: string[];
  skipped: string[];
  errors: string[];
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate .claude/rules/ instruction files for a project.
 *
 * @param repoRoot - Repository root directory
 * @param templateNames - Template names to generate (from adapter + global)
 * @returns Result with created, skipped, and errored files
 */
export async function generateRules(
  repoRoot: string,
  templateNames: string[],
): Promise<RuleGenerationResult> {
  const result: RuleGenerationResult = {
    created: [],
    skipped: [],
    errors: [],
  };

  const engine = new TemplateEngine();
  const rulesDir = join(repoRoot, ".claude", "rules");
  const variables: Record<string, unknown> = { version: VERSION };

  // Combine global + adapter-provided template names (deduplicated)
  const allTemplates = [...new Set([...GLOBAL_RULES, ...templateNames])];

  for (const name of allTemplates) {
    const templateFile = `rules/${name}.md`;
    const targetPath = join(rulesDir, `${name}.md`);

    try {
      if (!engine.hasTemplate(templateFile)) {
        result.errors.push(`Template not found: ${templateFile}`);
        continue;
      }

      const rendered = engine.render(templateFile, variables);

      if (!rendered.trim()) {
        result.errors.push(`Template rendered empty: ${templateFile}`);
        continue;
      }

      // Three-tier merge: check if existing file should be preserved
      if (existsSync(targetPath)) {
        const existing = readFileSync(targetPath, "utf-8");

        if (isUnmodified(existing, rendered)) {
          // Tier 1: Unmodified — auto-update silently
          await atomicWrite(targetPath, rendered);
          result.created.push(`${name}.md`);
        } else {
          // Tier 2: User-modified — preserve
          result.skipped.push(`${name}.md`);
        }
      } else {
        // Tier 3: New file — create
        await atomicWrite(targetPath, rendered);
        result.created.push(`${name}.md`);
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      result.errors.push(`${name}.md: ${msg}`);
    }
  }

  return result;
}

/**
 * Get the combined list of rule template names for a tech stack.
 * Includes global rules + adapter-specific rules.
 */
export function getRuleTemplateNames(
  adapterTemplates?: string[],
): string[] {
  return [...new Set([...GLOBAL_RULES, ...(adapterTemplates ?? [])])];
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Check if an existing file is unmodified from the template.
 *
 * A file is "unmodified" if its content matches the template content
 * when ignoring version numbers in the generated-by header.
 */
function isUnmodified(existing: string, template: string): boolean {
  // Normalize version headers for comparison
  const normalizeHeader = (s: string): string =>
    s.replace(VERSION_HEADER_PATTERN, "# Generated by dafke — do not edit manually");

  return normalizeHeader(existing).trim() === normalizeHeader(template).trim();
}
